- hosts: practica
  become: True
  tasks:

  - name: update
    action: command apt-get update -y
  - name: install java
    action: command apt install openjdk-11-jdk -y
  - name: java version
    action: command java -version
  - name: update
    apt:
      update_cache: yes
  - name: Install wget
    apt:
      name: wget
      state: present
  - name: Download foo.conf
    get_url:
      url: ttps://pkg.jenkins.io/debian-stable/jenkins.io.key
      dest: /home/asterionmorrigan
  - name: Key Add
    action: command apt-key add -
    
  - name: Jenkins List
    action: command sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \ /etc/apt/sources.list.d/jenkins.list'
  
